version: '3'

services:
  web:
    build: .
    command: sh -c "cd .. && ./manage.py collectstatic --noinput && ./manage.py migrate && daphne -b 0.0.0.0 -p 80 club.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./book_club:/book_club
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
