version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput  && daphne -b 0.0.0.0 -p 8000 club.asgi:application"
    restart: always
    volumes:
      - ./book_club:/book_club
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=database

  nginx:
    build: ./nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
